// Generated by CoffeeScript 2.3.2
require('coffeescript/register')
var gulp, i, len, ref, tsk;

gulp = require('gulp');

ref = 'clean coffee rename typescript remove webpack build-tasks'.split(/\s+/);
for (i = 0, len = ref.length; i < len; i++) {
  tsk = ref[i];
  require('./scripts-coffee/gulp-tasks/' + tsk);
}

gulp.task('default', ['webpack-server']);
